version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "challange"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgres/data
    networks:
      - infra-networks

networks:
  infra-networks:
    driver: bridge